### ISSUE TITLE
I can't run hunt-skeleton, I wait a long time, the whole computer hangs

### ISSUE THREAD

**Issue by TaniukO** [huntlabs/hunt-proton#2]
Performing "debug" build using /usr/bin/dmd for x86_64.
hunt 1.6.1: target for configuration "library" is up to date.
hunt-extra 1.0.0: target for configuration "library" is up to date.
hunt-net 0.5.1: target for configuration "default" is up to date.
hunt-time 1.1.1: target for configuration "library" is up to date.
hunt-proton 1.1.0-beta.3: building configuration "library"...
Killed
/usr/bin/dmd failed with exit code 137.

 it interrupts itself

**Comment by Heromyth** [comment]
It's so sorry. To build hunt-skeleton, a big memory (>8G) is required.
